# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binary_clock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(284, 364)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_01 = QtWidgets.QVBoxLayout()
        self.verticalLayout_01.setSpacing(0)
        self.verticalLayout_01.setObjectName("verticalLayout_01")
        self.horizontalLayout_08 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_08.setSpacing(0)
        self.horizontalLayout_08.setObjectName("horizontalLayout_08")
        self.label_08_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_08_08.setMinimumSize(QtCore.QSize(32, 32))
        self.label_08_08.setMaximumSize(QtCore.QSize(32, 32))
        self.label_08_08.setFrameShape(QtWidgets.QFrame.Box)
        self.label_08_08.setText("")
        self.label_08_08.setObjectName("label_08_08")
        self.horizontalLayout_08.addWidget(self.label_08_08)
        self.label_08_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_08_07.setMinimumSize(QtCore.QSize(32, 32))
        self.label_08_07.setMaximumSize(QtCore.QSize(32, 32))
        self.label_08_07.setFrameShape(QtWidgets.QFrame.Box)
        self.label_08_07.setText("")
        self.label_08_07.setObjectName("label_08_07")
        self.horizontalLayout_08.addWidget(self.label_08_07)
        self.label_08_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_08_06.setMinimumSize(QtCore.QSize(32, 32))
        self.label_08_06.setMaximumSize(QtCore.QSize(32, 32))
        self.label_08_06.setFrameShape(QtWidgets.QFrame.Box)
        self.label_08_06.setText("")
        self.label_08_06.setObjectName("label_08_06")
        self.horizontalLayout_08.addWidget(self.label_08_06)
        self.label_08_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_08_05.setMinimumSize(QtCore.QSize(32, 32))
        self.label_08_05.setMaximumSize(QtCore.QSize(32, 32))
        self.label_08_05.setFrameShape(QtWidgets.QFrame.Box)
        self.label_08_05.setText("")
        self.label_08_05.setObjectName("label_08_05")
        self.horizontalLayout_08.addWidget(self.label_08_05)
        self.label_08_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_08_04.setMinimumSize(QtCore.QSize(32, 32))
        self.label_08_04.setMaximumSize(QtCore.QSize(32, 32))
        self.label_08_04.setFrameShape(QtWidgets.QFrame.Box)
        self.label_08_04.setText("")
        self.label_08_04.setObjectName("label_08_04")
        self.horizontalLayout_08.addWidget(self.label_08_04)
        self.label_08_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_08_03.setMinimumSize(QtCore.QSize(32, 32))
        self.label_08_03.setMaximumSize(QtCore.QSize(32, 32))
        self.label_08_03.setFrameShape(QtWidgets.QFrame.Box)
        self.label_08_03.setText("")
        self.label_08_03.setObjectName("label_08_03")
        self.horizontalLayout_08.addWidget(self.label_08_03)
        self.label_08_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_08_02.setMinimumSize(QtCore.QSize(32, 32))
        self.label_08_02.setMaximumSize(QtCore.QSize(32, 32))
        self.label_08_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_08_02.setText("")
        self.label_08_02.setObjectName("label_08_02")
        self.horizontalLayout_08.addWidget(self.label_08_02)
        self.label_08_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_08_01.setMinimumSize(QtCore.QSize(32, 32))
        self.label_08_01.setMaximumSize(QtCore.QSize(32, 32))
        self.label_08_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_08_01.setText("")
        self.label_08_01.setObjectName("label_08_01")
        self.horizontalLayout_08.addWidget(self.label_08_01)
        self.verticalLayout_01.addLayout(self.horizontalLayout_08)
        self.horizontalLayout_07 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_07.setSpacing(0)
        self.horizontalLayout_07.setObjectName("horizontalLayout_07")
        self.label_07_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_07_08.setMinimumSize(QtCore.QSize(32, 32))
        self.label_07_08.setMaximumSize(QtCore.QSize(32, 32))
        self.label_07_08.setFrameShape(QtWidgets.QFrame.Box)
        self.label_07_08.setText("")
        self.label_07_08.setObjectName("label_07_08")
        self.horizontalLayout_07.addWidget(self.label_07_08)
        self.label_07_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_07_07.setMinimumSize(QtCore.QSize(32, 32))
        self.label_07_07.setMaximumSize(QtCore.QSize(32, 32))
        self.label_07_07.setFrameShape(QtWidgets.QFrame.Box)
        self.label_07_07.setText("")
        self.label_07_07.setObjectName("label_07_07")
        self.horizontalLayout_07.addWidget(self.label_07_07)
        self.label_07_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_07_06.setMinimumSize(QtCore.QSize(32, 32))
        self.label_07_06.setMaximumSize(QtCore.QSize(32, 32))
        self.label_07_06.setFrameShape(QtWidgets.QFrame.Box)
        self.label_07_06.setText("")
        self.label_07_06.setObjectName("label_07_06")
        self.horizontalLayout_07.addWidget(self.label_07_06)
        self.label_07_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_07_05.setMinimumSize(QtCore.QSize(32, 32))
        self.label_07_05.setMaximumSize(QtCore.QSize(32, 32))
        self.label_07_05.setFrameShape(QtWidgets.QFrame.Box)
        self.label_07_05.setText("")
        self.label_07_05.setObjectName("label_07_05")
        self.horizontalLayout_07.addWidget(self.label_07_05)
        self.label_07_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_07_04.setMinimumSize(QtCore.QSize(32, 32))
        self.label_07_04.setMaximumSize(QtCore.QSize(32, 32))
        self.label_07_04.setFrameShape(QtWidgets.QFrame.Box)
        self.label_07_04.setText("")
        self.label_07_04.setObjectName("label_07_04")
        self.horizontalLayout_07.addWidget(self.label_07_04)
        self.label_07_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_07_03.setMinimumSize(QtCore.QSize(32, 32))
        self.label_07_03.setMaximumSize(QtCore.QSize(32, 32))
        self.label_07_03.setFrameShape(QtWidgets.QFrame.Box)
        self.label_07_03.setText("")
        self.label_07_03.setObjectName("label_07_03")
        self.horizontalLayout_07.addWidget(self.label_07_03)
        self.label_07_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_07_02.setMinimumSize(QtCore.QSize(32, 32))
        self.label_07_02.setMaximumSize(QtCore.QSize(32, 32))
        self.label_07_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_07_02.setText("")
        self.label_07_02.setObjectName("label_07_02")
        self.horizontalLayout_07.addWidget(self.label_07_02)
        self.label_07_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_07_01.setMinimumSize(QtCore.QSize(32, 32))
        self.label_07_01.setMaximumSize(QtCore.QSize(32, 32))
        self.label_07_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_07_01.setText("")
        self.label_07_01.setObjectName("label_07_01")
        self.horizontalLayout_07.addWidget(self.label_07_01)
        self.verticalLayout_01.addLayout(self.horizontalLayout_07)
        self.horizontalLayout_06 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_06.setSpacing(0)
        self.horizontalLayout_06.setObjectName("horizontalLayout_06")
        self.label_06_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_06_08.setMinimumSize(QtCore.QSize(32, 32))
        self.label_06_08.setMaximumSize(QtCore.QSize(32, 32))
        self.label_06_08.setFrameShape(QtWidgets.QFrame.Box)
        self.label_06_08.setText("")
        self.label_06_08.setObjectName("label_06_08")
        self.horizontalLayout_06.addWidget(self.label_06_08)
        self.label_06_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_06_07.setMinimumSize(QtCore.QSize(32, 32))
        self.label_06_07.setMaximumSize(QtCore.QSize(32, 32))
        self.label_06_07.setFrameShape(QtWidgets.QFrame.Box)
        self.label_06_07.setText("")
        self.label_06_07.setObjectName("label_06_07")
        self.horizontalLayout_06.addWidget(self.label_06_07)
        self.label_06_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_06_06.setMinimumSize(QtCore.QSize(32, 32))
        self.label_06_06.setMaximumSize(QtCore.QSize(32, 32))
        self.label_06_06.setFrameShape(QtWidgets.QFrame.Box)
        self.label_06_06.setText("")
        self.label_06_06.setObjectName("label_06_06")
        self.horizontalLayout_06.addWidget(self.label_06_06)
        self.label_06_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_06_05.setMinimumSize(QtCore.QSize(32, 32))
        self.label_06_05.setMaximumSize(QtCore.QSize(32, 32))
        self.label_06_05.setFrameShape(QtWidgets.QFrame.Box)
        self.label_06_05.setText("")
        self.label_06_05.setObjectName("label_06_05")
        self.horizontalLayout_06.addWidget(self.label_06_05)
        self.label_06_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_06_04.setMinimumSize(QtCore.QSize(32, 32))
        self.label_06_04.setMaximumSize(QtCore.QSize(32, 32))
        self.label_06_04.setFrameShape(QtWidgets.QFrame.Box)
        self.label_06_04.setText("")
        self.label_06_04.setObjectName("label_06_04")
        self.horizontalLayout_06.addWidget(self.label_06_04)
        self.label_06_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_06_03.setMinimumSize(QtCore.QSize(32, 32))
        self.label_06_03.setMaximumSize(QtCore.QSize(32, 32))
        self.label_06_03.setFrameShape(QtWidgets.QFrame.Box)
        self.label_06_03.setText("")
        self.label_06_03.setObjectName("label_06_03")
        self.horizontalLayout_06.addWidget(self.label_06_03)
        self.label_06_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_06_02.setMinimumSize(QtCore.QSize(32, 32))
        self.label_06_02.setMaximumSize(QtCore.QSize(32, 32))
        self.label_06_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_06_02.setText("")
        self.label_06_02.setObjectName("label_06_02")
        self.horizontalLayout_06.addWidget(self.label_06_02)
        self.label_06_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_06_01.setMinimumSize(QtCore.QSize(32, 32))
        self.label_06_01.setMaximumSize(QtCore.QSize(32, 32))
        self.label_06_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_06_01.setText("")
        self.label_06_01.setObjectName("label_06_01")
        self.horizontalLayout_06.addWidget(self.label_06_01)
        self.verticalLayout_01.addLayout(self.horizontalLayout_06)
        self.horizontalLayout_05 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_05.setSpacing(0)
        self.horizontalLayout_05.setObjectName("horizontalLayout_05")
        self.label_05_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_05_08.setMinimumSize(QtCore.QSize(32, 32))
        self.label_05_08.setMaximumSize(QtCore.QSize(32, 32))
        self.label_05_08.setFrameShape(QtWidgets.QFrame.Box)
        self.label_05_08.setText("")
        self.label_05_08.setObjectName("label_05_08")
        self.horizontalLayout_05.addWidget(self.label_05_08)
        self.label_05_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_05_07.setMinimumSize(QtCore.QSize(32, 32))
        self.label_05_07.setMaximumSize(QtCore.QSize(32, 32))
        self.label_05_07.setFrameShape(QtWidgets.QFrame.Box)
        self.label_05_07.setText("")
        self.label_05_07.setObjectName("label_05_07")
        self.horizontalLayout_05.addWidget(self.label_05_07)
        self.label_05_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_05_06.setMinimumSize(QtCore.QSize(32, 32))
        self.label_05_06.setMaximumSize(QtCore.QSize(32, 32))
        self.label_05_06.setFrameShape(QtWidgets.QFrame.Box)
        self.label_05_06.setText("")
        self.label_05_06.setObjectName("label_05_06")
        self.horizontalLayout_05.addWidget(self.label_05_06)
        self.label_05_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_05_05.setMinimumSize(QtCore.QSize(32, 32))
        self.label_05_05.setMaximumSize(QtCore.QSize(32, 32))
        self.label_05_05.setFrameShape(QtWidgets.QFrame.Box)
        self.label_05_05.setText("")
        self.label_05_05.setObjectName("label_05_05")
        self.horizontalLayout_05.addWidget(self.label_05_05)
        self.label_05_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_05_04.setMinimumSize(QtCore.QSize(32, 32))
        self.label_05_04.setMaximumSize(QtCore.QSize(32, 32))
        self.label_05_04.setFrameShape(QtWidgets.QFrame.Box)
        self.label_05_04.setText("")
        self.label_05_04.setObjectName("label_05_04")
        self.horizontalLayout_05.addWidget(self.label_05_04)
        self.label_05_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_05_03.setMinimumSize(QtCore.QSize(32, 32))
        self.label_05_03.setMaximumSize(QtCore.QSize(32, 32))
        self.label_05_03.setFrameShape(QtWidgets.QFrame.Box)
        self.label_05_03.setText("")
        self.label_05_03.setObjectName("label_05_03")
        self.horizontalLayout_05.addWidget(self.label_05_03)
        self.label_05_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_05_02.setMinimumSize(QtCore.QSize(32, 32))
        self.label_05_02.setMaximumSize(QtCore.QSize(32, 32))
        self.label_05_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_05_02.setText("")
        self.label_05_02.setObjectName("label_05_02")
        self.horizontalLayout_05.addWidget(self.label_05_02)
        self.label_05_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_05_01.setMinimumSize(QtCore.QSize(32, 32))
        self.label_05_01.setMaximumSize(QtCore.QSize(32, 32))
        self.label_05_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_05_01.setText("")
        self.label_05_01.setObjectName("label_05_01")
        self.horizontalLayout_05.addWidget(self.label_05_01)
        self.verticalLayout_01.addLayout(self.horizontalLayout_05)
        self.horizontalLayout_04 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_04.setSpacing(0)
        self.horizontalLayout_04.setObjectName("horizontalLayout_04")
        self.label_04_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_04_08.setMinimumSize(QtCore.QSize(32, 32))
        self.label_04_08.setMaximumSize(QtCore.QSize(32, 32))
        self.label_04_08.setFrameShape(QtWidgets.QFrame.Box)
        self.label_04_08.setText("")
        self.label_04_08.setObjectName("label_04_08")
        self.horizontalLayout_04.addWidget(self.label_04_08)
        self.label_04_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_04_07.setMinimumSize(QtCore.QSize(32, 32))
        self.label_04_07.setMaximumSize(QtCore.QSize(32, 32))
        self.label_04_07.setFrameShape(QtWidgets.QFrame.Box)
        self.label_04_07.setText("")
        self.label_04_07.setObjectName("label_04_07")
        self.horizontalLayout_04.addWidget(self.label_04_07)
        self.label_04_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_04_06.setMinimumSize(QtCore.QSize(32, 32))
        self.label_04_06.setMaximumSize(QtCore.QSize(32, 32))
        self.label_04_06.setFrameShape(QtWidgets.QFrame.Box)
        self.label_04_06.setText("")
        self.label_04_06.setObjectName("label_04_06")
        self.horizontalLayout_04.addWidget(self.label_04_06)
        self.label_04_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_04_05.setMinimumSize(QtCore.QSize(32, 32))
        self.label_04_05.setMaximumSize(QtCore.QSize(32, 32))
        self.label_04_05.setFrameShape(QtWidgets.QFrame.Box)
        self.label_04_05.setText("")
        self.label_04_05.setObjectName("label_04_05")
        self.horizontalLayout_04.addWidget(self.label_04_05)
        self.label_04_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_04_04.setMinimumSize(QtCore.QSize(32, 32))
        self.label_04_04.setMaximumSize(QtCore.QSize(32, 32))
        self.label_04_04.setFrameShape(QtWidgets.QFrame.Box)
        self.label_04_04.setText("")
        self.label_04_04.setObjectName("label_04_04")
        self.horizontalLayout_04.addWidget(self.label_04_04)
        self.label_04_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_04_03.setMinimumSize(QtCore.QSize(32, 32))
        self.label_04_03.setMaximumSize(QtCore.QSize(32, 32))
        self.label_04_03.setFrameShape(QtWidgets.QFrame.Box)
        self.label_04_03.setText("")
        self.label_04_03.setObjectName("label_04_03")
        self.horizontalLayout_04.addWidget(self.label_04_03)
        self.label_04_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_04_02.setMinimumSize(QtCore.QSize(32, 32))
        self.label_04_02.setMaximumSize(QtCore.QSize(32, 32))
        self.label_04_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_04_02.setText("")
        self.label_04_02.setObjectName("label_04_02")
        self.horizontalLayout_04.addWidget(self.label_04_02)
        self.label_04_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_04_01.setMinimumSize(QtCore.QSize(32, 32))
        self.label_04_01.setMaximumSize(QtCore.QSize(32, 32))
        self.label_04_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_04_01.setText("")
        self.label_04_01.setObjectName("label_04_01")
        self.horizontalLayout_04.addWidget(self.label_04_01)
        self.verticalLayout_01.addLayout(self.horizontalLayout_04)
        self.horizontalLayout_03 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_03.setSpacing(0)
        self.horizontalLayout_03.setObjectName("horizontalLayout_03")
        self.label_03_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_03_08.setMinimumSize(QtCore.QSize(32, 32))
        self.label_03_08.setMaximumSize(QtCore.QSize(32, 32))
        self.label_03_08.setFrameShape(QtWidgets.QFrame.Box)
        self.label_03_08.setText("")
        self.label_03_08.setObjectName("label_03_08")
        self.horizontalLayout_03.addWidget(self.label_03_08)
        self.label_03_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_03_07.setMinimumSize(QtCore.QSize(32, 32))
        self.label_03_07.setMaximumSize(QtCore.QSize(32, 32))
        self.label_03_07.setFrameShape(QtWidgets.QFrame.Box)
        self.label_03_07.setText("")
        self.label_03_07.setObjectName("label_03_07")
        self.horizontalLayout_03.addWidget(self.label_03_07)
        self.label_03_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_03_06.setMinimumSize(QtCore.QSize(32, 32))
        self.label_03_06.setMaximumSize(QtCore.QSize(32, 32))
        self.label_03_06.setFrameShape(QtWidgets.QFrame.Box)
        self.label_03_06.setText("")
        self.label_03_06.setObjectName("label_03_06")
        self.horizontalLayout_03.addWidget(self.label_03_06)
        self.label_03_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_03_05.setMinimumSize(QtCore.QSize(32, 32))
        self.label_03_05.setMaximumSize(QtCore.QSize(32, 32))
        self.label_03_05.setFrameShape(QtWidgets.QFrame.Box)
        self.label_03_05.setText("")
        self.label_03_05.setObjectName("label_03_05")
        self.horizontalLayout_03.addWidget(self.label_03_05)
        self.label_03_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_03_04.setMinimumSize(QtCore.QSize(32, 32))
        self.label_03_04.setMaximumSize(QtCore.QSize(32, 32))
        self.label_03_04.setFrameShape(QtWidgets.QFrame.Box)
        self.label_03_04.setText("")
        self.label_03_04.setObjectName("label_03_04")
        self.horizontalLayout_03.addWidget(self.label_03_04)
        self.label_03_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_03_03.setMinimumSize(QtCore.QSize(32, 32))
        self.label_03_03.setMaximumSize(QtCore.QSize(32, 32))
        self.label_03_03.setFrameShape(QtWidgets.QFrame.Box)
        self.label_03_03.setText("")
        self.label_03_03.setObjectName("label_03_03")
        self.horizontalLayout_03.addWidget(self.label_03_03)
        self.label_03_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_03_02.setMinimumSize(QtCore.QSize(32, 32))
        self.label_03_02.setMaximumSize(QtCore.QSize(32, 32))
        self.label_03_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_03_02.setText("")
        self.label_03_02.setObjectName("label_03_02")
        self.horizontalLayout_03.addWidget(self.label_03_02)
        self.label_03_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_03_01.setMinimumSize(QtCore.QSize(32, 32))
        self.label_03_01.setMaximumSize(QtCore.QSize(32, 32))
        self.label_03_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_03_01.setText("")
        self.label_03_01.setObjectName("label_03_01")
        self.horizontalLayout_03.addWidget(self.label_03_01)
        self.verticalLayout_01.addLayout(self.horizontalLayout_03)
        self.horizontalLayout_02 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_02.setSpacing(0)
        self.horizontalLayout_02.setObjectName("horizontalLayout_02")
        self.label_02_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_02_08.setMinimumSize(QtCore.QSize(32, 32))
        self.label_02_08.setMaximumSize(QtCore.QSize(32, 32))
        self.label_02_08.setFrameShape(QtWidgets.QFrame.Box)
        self.label_02_08.setText("")
        self.label_02_08.setObjectName("label_02_08")
        self.horizontalLayout_02.addWidget(self.label_02_08)
        self.label_02_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_02_07.setMinimumSize(QtCore.QSize(32, 32))
        self.label_02_07.setMaximumSize(QtCore.QSize(32, 32))
        self.label_02_07.setFrameShape(QtWidgets.QFrame.Box)
        self.label_02_07.setText("")
        self.label_02_07.setObjectName("label_02_07")
        self.horizontalLayout_02.addWidget(self.label_02_07)
        self.label_02_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_02_06.setMinimumSize(QtCore.QSize(32, 32))
        self.label_02_06.setMaximumSize(QtCore.QSize(32, 32))
        self.label_02_06.setFrameShape(QtWidgets.QFrame.Box)
        self.label_02_06.setText("")
        self.label_02_06.setObjectName("label_02_06")
        self.horizontalLayout_02.addWidget(self.label_02_06)
        self.label_02_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_02_05.setMinimumSize(QtCore.QSize(32, 32))
        self.label_02_05.setMaximumSize(QtCore.QSize(32, 32))
        self.label_02_05.setFrameShape(QtWidgets.QFrame.Box)
        self.label_02_05.setText("")
        self.label_02_05.setObjectName("label_02_05")
        self.horizontalLayout_02.addWidget(self.label_02_05)
        self.label_02_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_02_04.setMinimumSize(QtCore.QSize(32, 32))
        self.label_02_04.setMaximumSize(QtCore.QSize(32, 32))
        self.label_02_04.setFrameShape(QtWidgets.QFrame.Box)
        self.label_02_04.setText("")
        self.label_02_04.setObjectName("label_02_04")
        self.horizontalLayout_02.addWidget(self.label_02_04)
        self.label_02_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_02_03.setMinimumSize(QtCore.QSize(32, 32))
        self.label_02_03.setMaximumSize(QtCore.QSize(32, 32))
        self.label_02_03.setFrameShape(QtWidgets.QFrame.Box)
        self.label_02_03.setText("")
        self.label_02_03.setObjectName("label_02_03")
        self.horizontalLayout_02.addWidget(self.label_02_03)
        self.label_02_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_02_02.setMinimumSize(QtCore.QSize(32, 32))
        self.label_02_02.setMaximumSize(QtCore.QSize(32, 32))
        self.label_02_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_02_02.setText("")
        self.label_02_02.setObjectName("label_02_02")
        self.horizontalLayout_02.addWidget(self.label_02_02)
        self.label_02_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_02_01.setMinimumSize(QtCore.QSize(32, 32))
        self.label_02_01.setMaximumSize(QtCore.QSize(32, 32))
        self.label_02_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_02_01.setText("")
        self.label_02_01.setObjectName("label_02_01")
        self.horizontalLayout_02.addWidget(self.label_02_01)
        self.verticalLayout_01.addLayout(self.horizontalLayout_02)
        self.horizontalLayout_01 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_01.setSpacing(0)
        self.horizontalLayout_01.setObjectName("horizontalLayout_01")
        self.label_01_08 = QtWidgets.QLabel(self.centralwidget)
        self.label_01_08.setMinimumSize(QtCore.QSize(32, 32))
        self.label_01_08.setMaximumSize(QtCore.QSize(32, 32))
        self.label_01_08.setFrameShape(QtWidgets.QFrame.Box)
        self.label_01_08.setText("")
        self.label_01_08.setObjectName("label_01_08")
        self.horizontalLayout_01.addWidget(self.label_01_08)
        self.label_01_07 = QtWidgets.QLabel(self.centralwidget)
        self.label_01_07.setMinimumSize(QtCore.QSize(32, 32))
        self.label_01_07.setMaximumSize(QtCore.QSize(32, 32))
        self.label_01_07.setFrameShape(QtWidgets.QFrame.Box)
        self.label_01_07.setText("")
        self.label_01_07.setObjectName("label_01_07")
        self.horizontalLayout_01.addWidget(self.label_01_07)
        self.label_01_06 = QtWidgets.QLabel(self.centralwidget)
        self.label_01_06.setMinimumSize(QtCore.QSize(32, 32))
        self.label_01_06.setMaximumSize(QtCore.QSize(32, 32))
        self.label_01_06.setFrameShape(QtWidgets.QFrame.Box)
        self.label_01_06.setText("")
        self.label_01_06.setObjectName("label_01_06")
        self.horizontalLayout_01.addWidget(self.label_01_06)
        self.label_01_05 = QtWidgets.QLabel(self.centralwidget)
        self.label_01_05.setMinimumSize(QtCore.QSize(32, 32))
        self.label_01_05.setMaximumSize(QtCore.QSize(32, 32))
        self.label_01_05.setFrameShape(QtWidgets.QFrame.Box)
        self.label_01_05.setText("")
        self.label_01_05.setObjectName("label_01_05")
        self.horizontalLayout_01.addWidget(self.label_01_05)
        self.label_01_04 = QtWidgets.QLabel(self.centralwidget)
        self.label_01_04.setMinimumSize(QtCore.QSize(32, 32))
        self.label_01_04.setMaximumSize(QtCore.QSize(32, 32))
        self.label_01_04.setFrameShape(QtWidgets.QFrame.Box)
        self.label_01_04.setText("")
        self.label_01_04.setObjectName("label_01_04")
        self.horizontalLayout_01.addWidget(self.label_01_04)
        self.label_01_03 = QtWidgets.QLabel(self.centralwidget)
        self.label_01_03.setMinimumSize(QtCore.QSize(32, 32))
        self.label_01_03.setMaximumSize(QtCore.QSize(32, 32))
        self.label_01_03.setFrameShape(QtWidgets.QFrame.Box)
        self.label_01_03.setText("")
        self.label_01_03.setObjectName("label_01_03")
        self.horizontalLayout_01.addWidget(self.label_01_03)
        self.label_01_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_01_02.setMinimumSize(QtCore.QSize(32, 32))
        self.label_01_02.setMaximumSize(QtCore.QSize(32, 32))
        self.label_01_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_01_02.setText("")
        self.label_01_02.setObjectName("label_01_02")
        self.horizontalLayout_01.addWidget(self.label_01_02)
        self.label_01_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_01_01.setMinimumSize(QtCore.QSize(32, 32))
        self.label_01_01.setMaximumSize(QtCore.QSize(32, 32))
        self.label_01_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_01_01.setText("")
        self.label_01_01.setObjectName("label_01_01")
        self.horizontalLayout_01.addWidget(self.label_01_01)
        self.verticalLayout_01.addLayout(self.horizontalLayout_01)
        self.horizontalLayout_09 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_09.setObjectName("horizontalLayout_09")
        self.label_Current_Time_Str = QtWidgets.QLabel(self.centralwidget)
        self.label_Current_Time_Str.setMinimumSize(QtCore.QSize(0, 32))
        self.label_Current_Time_Str.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_Current_Time_Str.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Current_Time_Str.setText("")
        self.label_Current_Time_Str.setObjectName("label_Current_Time_Str")
        self.horizontalLayout_09.addWidget(self.label_Current_Time_Str)
        self.verticalLayout_01.addLayout(self.horizontalLayout_09)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout_10.addWidget(self.pushButton_Start)
        self.verticalLayout_01.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.verticalLayout_01)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Binary Clock"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))

